version: "3"

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  web:
    build: .
    command: python3 manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
